apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cni-plugins-daemonset
spec:
  selector:
    matchLabels:
      app: cni-plugins
  template:
    metadata:
      labels:
        app: cni-plugins
    spec:
      # We want to schedule this on all nodes.
      tolerations:
      - operator: Exists
        effect: NoSchedule
      # We need this so that it can run without flannel.
      hostNetwork: true
      initContainers:
      - name: copy-cni-plugins
        image: dougbtv/cni-plugins
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - cp -r /cni-plugins/bin/* /opt/cni/bin
        volumeMounts:
        - name: cni-bin
          mountPath: /opt/cni/bin
      containers:
      - name: cni-ref-sleeper
        image: dougbtv/cni-plugins
        command: ["sleep", "360000000"]
        volumeMounts:
        - name: cni-bin
          mountPath: /opt/cni/bin
      volumes:
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
