apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cni-plugins-daemonset
spec:
  selector:
    matchLabels:
      app: cni-plugins
  template:
    metadata:
      labels:
        app: cni-plugins
    spec:
      nodeSelector:   # Add node selector here
        node-role.kubernetes.io/master: ""
      hostNetwork: true   # Add host networking configuration
      initContainers:
      - name: copy-cni-plugins
        image: dougbtv/cni-plugins
        command:
        - /bin/sh
        - -c
        - cp -r /cni-plugins/bin/* /opt/cni/bin
        volumeMounts:
        - name: cni-bin
          mountPath: /opt/cni/bin
      containers:
      - name: alpine-container
        image: alpine:latest
        command: ["sleep", "3600"]
      volumes:
      - name: cni-bin
        emptyDir: {}
